apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: collectorset-controller
  labels:
    chart: "collectorset-controller"
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: collectorset-controller
    spec:
      serviceAccountName: collectorset-controller
      affinity:
      nodeSelector:
      containers:
      - name: collectorset-controller
        image: logicmonitor/collectorset-controller:latest.v1
        imagePullPolicy: Always
        env:
        - name: ACCESS_ID
          valueFrom:
            secretKeyRef:
              name: collectorset-controller
              key: accessID
        - name: ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: collectorset-controller
              key: accessKey
        - name: ACCOUNT
          valueFrom:
            secretKeyRef:
              name: collectorset-controller
              key: account
        - name: ETCD_DISCOVERY_TOKEN
          valueFrom:
            secretKeyRef:
              name: collectorset-controller
              key: etcdDiscoveryToken
  # to vaslidate does proxy user and pass exist or not
        volumeMounts:
        - name: etc-collectorset-controller
          mountPath: "/etc/collectorset-controller"
          readOnly: true
      volumes:
      - name: etc-collectorset-controller
        projected:
          sources:
          - configMap:
              name: collectorset-controller
              items:
                - key: config.yaml
                  path: config.yaml
