apiVersion: v1
kind: Secret
metadata:
  name: collectorset-controller
type: Opaque
data:
  accessID: 2ncvPufefCX9vtEL3Lx9
  accessKey: ~27~WdH2qZwi(z86nux6~[Bf(9RW]yi2r6z[PCFS
  account: cdkglobal
  etcdDiscoveryToken: 
  #to be validate proxy user and pass
