---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: collectorset-controller
  namespace: cloudplatform
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: collector
  namespace: cloudplatform
