apiVersion: logicmonitor.com/v1alpha1
kind: CollectorSet
metadata:
  name: {{ lower .Values.clusterName }}
  namespace: {{ .Release.Namespace }}
spec:
  policy:
    distributionStrategy: RoundRobin
    orchestrator: Kubernetes
  replicas: {{ required "A valid .Values.collector.replicas entry is required!" .Values.collector.replicas }}
  size: {{ required "A valid .Values.collector.size entry is required!" .Values.collector.size }}
  clusterName: {{ required "A valid .Values.clusterName entry is required!" .Values.clusterName }}
  {{- if .Values.collector.groupID }}
  groupID:  {{ .Values.collector.groupID }}
  {{- end }}
  {{- if .Values.collector.escalationChainID }}
  escalationChainID: {{ .Values.collector.escalationChainID }}
  {{- end }}
  {{- if .Values.collector.collectorVersion }}
  collectorVersion: {{ .Values.collector.collectorVersion }}
  {{- end }}
  {{- if .Values.collector.useEA }}
  useEA: {{ .Values.collector.useEA }}
  {{- end }}
  {{- if .Values.collector.proxyURL }}
  proxyURL: {{ .Values.collector.proxyURL }}
  {{- end }}
  {{- if .Values.collector.proxyUser }}
  secretName: {{ required "A valid .Values.collector.secretName entry is required!" .Values.collector.secretName }}
  {{- end }}
