apiVersion: logicmonitor.com/v1alpha1
kind: CollectorSet
metadata:
  name: lab1-ord
  namespace: {{ .Release.Namespace }}
spec:
  policy:
    distributionStrategy: RoundRobin
    orchestrator: Kubernetes
  replicas: {{ required "A valid .Values.collector.replicas entry is required!" .Values.collector.replicas }}
  size: {{ required "A valid .Values.collector.size entry is required!" .Values.collector.size }}
  clusterName: lab1-ord
  {{- if .Values.collector.groupID }}
  groupID:  {{ .Values.collector.groupID }}
  {{- end }}
  {{- if .Values.collector.escalationChainID }}
  escalationChainID: {{ .Values.collector.escalationChainID }}
  {{- end }}
  {{- if .Values.collector.collectorVersion }}
  collectorVersion: {{ .Values.collector.collectorVersion }}
  useEA: {{ .Values.collector.useEA }}
  proxyURL: ""
  secretName: {{ required "A valid .Values.collector.secretName entry is required!" .Values.collector.secretName }}
  {{- end }}
