apiVersion: v1
kind: ConfigMap
metadata:
  name: argus
data:
  config.yaml: |
    address: collectorset-controller:50000
    cluster_name: lab1-ord
    debug: false
    delete_devices: true
    disable_alerting: false
    etcd_discovery_token: 
    cluster_group_id: 
    
