apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: argus
  labels:
    chart: "argus"
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: argus
    spec:
      serviceAccountName: argus
      affinity:#to be vaildated
      nodeSelector:
      containers:
      - name: argus
        image: logicmonitor/argus
        imagePullPolicy: Always
        args:
          - watch
        env:
        - name: ACCESS_ID
          valueFrom:
            secretKeyRef:
              name: argus
              key: accessID
        - name: ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: argus
              key: accessKey
        - name: ACCOUNT
          valueFrom:
            secretKeyRef:
              name: argus
              key: account
        - name: ETCD_DISCOVERY_TOKEN
          valueFrom:
            secretKeyRef:
              name: argus
              key: etcdDiscoveryToken
        volumeMounts:
        - name: etc-argus
          mountPath: "/etc/argus"
          readOnly: true
      volumes:
      - name: etc-argus
        projected:
          sources:
          - configMap:
              name: argus
              items:
                - key: config.yaml
                  path: config.yaml
