apiVersion: v1
kind: Secret
metadata:
  name: argus
type: Opaque
data:
  accessID: 2ncvPufefCX9vtEL3Lx9
  accessKey: ~27~WdH2qZwi(z86nux6~[Bf(9RW]yi2r6z[PCFS
  account: cdkglobal
  etcdDiscoveryToken: "" 
  #to be validated
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ required "A valid .Values.collector.secretName entry is required!" .Values.collector.secretName }}
type: Opaque
data:
  proxyUser: 
  proxyPass: 
# to be validated proxy user and pass can keep blank
